# Generated by Django 4.0.3 on 2022-06-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('price', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('rating', models.CharField(blank=True, max_length=100, null=True)),
                ('rating_count', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
