# Generated by Django 4.0.3 on 2022-06-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okazje_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='rating',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
