# Generated by Django 4.0.3 on 2022-06-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okazje_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='rating',
            field=models.CharField(max_length=100),
        ),
    ]
