# Generated by Django 4.0.3 on 2022-06-13 10:34

from django.db import migrations, models
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('okazje_app', '0002_item_image_url_alter_item_image_alter_item_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=thumbnails.fields.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='rating',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
