# Generated by Django 4.0.3 on 2022-06-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okazje_app', '0002_alter_item_price_alter_item_rating_alter_item_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
