# Generated by Django 4.0.3 on 2022-07-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okazje_app', '0005_gotodata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_clicks', models.IntegerField(default=0)),
            ],
        ),
    ]
