# Generated by Django 4.0.3 on 2022-07-26 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('okazje_app', '0007_event_delete_events'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoToData',
        ),
    ]
