# Generated by Django 4.0.3 on 2022-07-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okazje_app', '0008_delete_gotodata'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
